image: node:9.2.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install hexo-cli -g
  - npm install
  - npm install hexo-neat --save
  - npm install hexo-helper-live2d --save
  - npm install hexo-generator-searchdb --save
  - npm install hexo-generator-baidu-sitemap --save
  - npm install hexo-generator-sitemap --save
  - npm install hexo-generator-feed --save
  - npm install hexo-autonofollow --save
  - npm install hexo-wordcount --save
  # - npm install --save hexo-algolia
  # - export HEXO_ALGOLIA_INDEXING_KEY=你的Key
  # - hexo algolia
  - hexo deploy
  artifacts:
    paths:
    - public
  only:
  - master
